language: rust
rust:
  - stable
  - beta
  - nightly
services:
  - postgresql
matrix:
  allow_failures:
    - rust: nightly
before_script:
    - |
        pip install 'travis-cargo<0.2' --user &&
        export PATH=$HOME/.local/bin:$PATH
script:
    - |
        travis-cargo build &&
        travis-cargo test -- --verbose --all-features &&
        travis-cargo --only nightly test -- --verbose --all-features -Z minimal-versions &&
        travis-cargo --only stable doc
env:
    global:
        - TRAVIS_CARGO_NIGHTLY_FEATURE=""
